# Generated by Django 4.0.6 on 2022-07-10 15:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alleles',
            fields=[
                ('id', models.AutoField(help_text='ID варианта', primary_key=True, serialize=False)),
                ('allele', models.CharField(blank=True, help_text='["REF","ALT"]', max_length=150, verbose_name='REF-ALT')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата изменения')),
                ('user_id', models.ForeignKey(help_text='Имя пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'REF-ALT',
                'verbose_name_plural': 'REF-ALT',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(help_text='ID', primary_key=True, serialize=False)),
                ('IID', models.CharField(max_length=25, verbose_name='Внутренний ID образца')),
                ('Lab_ID', models.CharField(max_length=25, verbose_name='Лабораторный номер')),
                ('Composition', models.CharField(max_length=200, verbose_name='Состав исследования')),
                ('Method', models.CharField(max_length=200, verbose_name='Метод исследования')),
                ('Pathology', models.CharField(max_length=100, verbose_name='Патологические мутации')),
                ('Platform', models.CharField(max_length=170, verbose_name='Платформа')),
                ('Result', models.TextField(max_length=500, verbose_name='Результаn')),
                ('status', models.BooleanField(verbose_name='Статус')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'случай',
                'verbose_name_plural': 'Случаи',
                'ordering': ['IID'],
            },
        ),
        migrations.CreateModel(
            name='Locus',
            fields=[
                ('id', models.AutoField(help_text='ID варианта', primary_key=True, serialize=False)),
                ('locus', models.CharField(blank=True, help_text='chr:position', max_length=25, verbose_name='Локус')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата изменения')),
                ('user_id', models.ForeignKey(help_text='Имя пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Локус',
                'verbose_name_plural': 'Локусы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(help_text='ID варианта', primary_key=True, serialize=False)),
                ('zig', models.CharField(blank=True, choices=[(0, '0/1'), (1, '1/1'), (2, '1/2'), (3, '0/2'), (4, '0/0'), (5, '0/3'), (6, '2/3'), (7, '1/3'), (8, '0/4'), (9, '1/4'), (10, '3/4')], help_text='Выберите зиготность', max_length=3, verbose_name='Зиготность')),
                ('vus', models.CharField(blank=True, choices=[(0, 'Pathogenic'), (1, 'Likely pathogenic'), (2, 'Uncertain significance'), (3, 'Likely benign'), (4, 'Benign')], help_text='Оценка патологичности варианта', max_length=50, verbose_name='Variants of Uncertain Significance')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата изменения')),
                ('alleles', models.ForeignKey(help_text='Выберите пару REF-ALT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='varbase.alleles', verbose_name='Аллели')),
                ('id_с', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='varbase.case', verbose_name='ID случая')),
                ('locus', models.ForeignKey(help_text='Выберите локус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='varbase.locus', verbose_name='Локус')),
                ('user_id', models.ForeignKey(help_text='Имя пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['-date'],
            },
        ),
    ]
